const menu = [
    {
        id: 1,
        title: 'Special Drinks 1',
        category: 'drinks',
        price: 7.79,
        img: './imgs/img-01.jpg',
        desc: `Sed id magna vitae eros sagittis euismod. `,
    },
    {
        id: 2,
        title: 'Special Drinks 2',
        category: 'drinks',
        price: 9.79,
        img: './imgs/img-02.jpg',
        desc: `Sed id magna vitae eros sagittis euismod. `,
    },
    {
        id: 3,
        title: 'Special Drinks 3',
        category: 'drinks',
        price: 7.77,
        img: './imgs/img-03.jpg',
        desc: `Sed id magna vitae eros sagittis euismod. `,
    },
    {
        id: 4,
        title: 'Special Lunch 1',
        category: 'lunch',
        price: 7.79,
        img: './imgs/img-04.jpg',
        desc: `Sed id magna vitae eros sagittis euismod. `,
    },
    {
        id: 5,
        title: 'Special Lunch 2',
        category: 'lunch',
        price: 10.77,
        img: './imgs/img-05.jpg',
        desc: `Sed id magna vitae eros sagittis euismod. `,
    },
    {
        id: 6,
        title: 'Special Lunch 3',
        category: 'lunch',
        price: 17.79,
        img: './imgs/img-06.jpg',
        desc: `Sed id magna vitae eros sagittis euismod. `,
    },
    {
        id: 7,
        title: 'Special Dinner 1',
        category: 'dinner',
        price: 10.79,
        img: './imgs/img-07.jpg',
        desc: `Sed id magna vitae eros sagittis euismod. `,
    },
    {
        id: 8,
        title: 'Special Dinner 2',
        category: 'dinner',
        price: 17.9,
        img: './imgs/img-08.jpg',
        desc: `Sed id magna vitae eros sagittis euismod. `,
    },
    {
        id: 9,
        title: 'Special Dinner 3',
        category: 'dinner',
        price: 27.79,
        img: './imgs/img-09.jpg',
        desc: `Sed id magna vitae eros sagittis euismod. `,
    },
]

export default menu